name: Force Fail
on:
  push:
    branches: [main]
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: This will fail
        run: |
          echo "failing now"
          exit 1
        shell: bash
